name: TicTacToeCIProg

on:
  push:
    branches:
      - develop
      - feature/develop/task5
  pull_request:
    branches:
      - develop

jobs:
  b_client:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2  
        with:
          vs-version: '16.0'

      - name: Restore NuGet packages
        run: nuget restore src/client/client.sln

      - name: Build solution
        run: |
          msbuild src/client/client.sln /p:Configuration=Release /p:Platform="x64" /p:OutputPath="src/client/build"

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: client-exe
          path: src/client/x64/Release/*.exe

  b_server:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Run hw-script.ps1
        shell: pwsh
        run: |
            .\ci\hw.ps1

      - name: Upload Arduino binaries
        uses: actions/upload-artifact@v4 
        with:
          name: server-hex
          path: ./ci/build/server/server.ino.hex
  
  b_docs:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run documentation script
        shell: pwsh
        run: |
          .\ci\doc.ps1

      - name: Upload Doxygen documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxy-html
          path: ./ci/docs/html

      - name: Upload Doxyfile
        uses: actions/upload-artifact@v4
        with:
          name: doxy-file
          path: ./ci/docs/Doxyfile

  b_test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2  
        with:
          vs-version: '16.0'

      - name: Restore NuGet packages
        run: nuget restore tests/test_client/test_client.sln

      - name: Run tests-script.ps1
        shell: pwsh
        run: |
            .\ci\tests.ps1

      - name: Upload test result
        uses: actions/upload-artifact@v4 
        with:
          name: client-test-result
          path: .\ci\test_result\client\TestResultClient.html

      - name: Upload test code coverage
        uses: actions/upload-artifact@v4 
        with:
          name: client-coverage-report
          path: .\ci\test_result\coverage_report_client